### PR TITLE
Add protocol version to request

### PR DESCRIPTION
**Pull request by WyriHaximus**
Currently the request is lacking the HTTP version from the PSR-7 request. This PR adds that to the request

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR! :+1:

Can you add a test to confirm this actually works?

The reason I'm asking is, this lib also works on PHP 5.3 which has to use http-client v0.3, which does not support this argument. I'm fine with this, but we should test and document this accordingly.

**Comment by WyriHaximus** [comment]
Yes I just did, after looking at `Sender` again I realized that I completely missed that the constructor is public and thus this is testable. I'm aware of that :+1:

**Comment by WyriHaximus** [comment]
Took longer then expected but fixed the tests to work for both `0.3` and `0.4`.

**Comment by clue** [comment]
Thanks for the update! :+1: 

Just to make this more obvious, can you add a functional test case (against httpbin), also to document the default behavior?

**Comment by WyriHaximus** [comment]
Sure thing, I'll research and add that :+1:

**Comment by WyriHaximus** [comment]
There doesn't seem to be a way to get the HTTP version from HTTPBin, but since it's opensource and on [github](https://github.com/Runscope/httpbin) I'll give it a go adding that.

**Comment by clue** [comment]
> There doesn't seem to be a way to get the HTTP version from HTTPBin, but since it's opensource and on github I'll give it a go adding that.

Duh, my bad! If you're going to add this to HTTPBin, this would be super-awesome! Otherwise, I'm *fine* with ditching my request and would accept just adding some documentation for this in the meantime :+1:

**Comment by WyriHaximus** [comment]
> > There doesn't seem to be a way to get the HTTP version from HTTPBin, but since it's opensource and on github I'll give it a go adding that.

> Duh, my bad! If you're going to add this to HTTPBin, this would be super-awesome! Otherwise, I'm fine with ditching my request and would accept just adding some documentation for this in the meantime :+1:

Lets see what the fine people at httpbin have to say about this first: https://github.com/Runscope/httpbin/pull/305 :wink:

**Comment by WyriHaximus** [comment]
Seems https://github.com/Runscope/httpbin/pull/305 is taking longer then hope/expected. I'll add code documentation, do you want anything in the readme as well?

**Comment by clue** [comment]
Too bad, but I guess just documentation is just fine for now :+1: Just describe the default behavior and how (and when) this can be changed and then let's get this in :shipit:

**Comment by WyriHaximus** [comment]
Will do, I already have the unit tests adapted but not committed yet. So once this PR is merged, I'll file a new one after with the updated tests.

**Comment by WyriHaximus** [comment]
Added a note about it. Not sure if this is the right place, it was the best I could find though.

**Comment by clue** [comment]
Thanks, let's get this in! :+1:

**Comment by WyriHaximus** [comment]
:tada: !

**Comment by clue** [comment]
See also #59 which builds on top of this and reverts the default protocol version back to HTTP/1.0.

**Comment by WyriHaximus** [comment]
Good catch, because this PR would technically introduce a BC

**Pull request merged**
