### PR TITLE
Expose Transaction options via Browser

### LINKED ISSUE #15: Expose transaction settings to outside
The `Transaction` has several settings such as `followRedirects`, `maxRedirects` and `obeySuccessCode`. However, there's currently no way to control these from the calling script.

### PR DESCRIPTION
**Pull request by clue**
Closes #15

### CODE REVIEW

**Comment by asm89** [comment]
@clue LGTM :+1: 

API wise it could be nice to extract a configuration object instead of doing the array and property exist stuff?

**Comment by clue** [comment]
> API wise it could be nice […]

Thanks for your feedback! :+1: I wholeheartedly agree, this API is anything but nice :)

Despite this, this library is considered beta and I'd love to get this feature out. IMO this PR implements a feature that is long overdue. Perhaps we should postpone the API discussion and move this to a dedicated tick?

**Comment by asm89** [comment]
@clue Sounds good. Ship this and shape up the API later. I'd just recommend doing that before the first stable. :+1:

**Comment by clue** [comment]
> @clue Sounds good. Ship this and shape up the API later. I'd just recommend doing that before the first stable. :+1:

I agree, please feel free to file a new ticket if you happen to have an idea for a better API and I'd love to get this in :+1:

**Pull request merged**
