### PR TITLE
Upgrade to new ReactPHP components

### PR DESCRIPTION
**Pull request by nick4fake**

### CODE REVIEW

**Comment by nick4fake** [comment]
#62

**Comment by clue** [comment]
Thanks for filing this, I think this is a good first step :+1: Unfortunately, it currently causes the tests to fail.

**Comment by nick4fake** [comment]
@clue I'll check, looks like I have missed one commit

**Comment by clue** [comment]
Thank you for filing this PR and getting the ball rolling! :+1:

This has just been resolved via #79, see also #62

**Pull request closed without merging**
